/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Bhuwan.gui.SwingDemo;

import java.awt.Color;

/**
 *
 * @author Bhuwan Pandey
 */
public class Check_ColorChanger extends javax.swing.JFrame {

    /**
     * Creates new form Check_ColorChanger
     */
    Color oldColor;
    public Check_ColorChanger() {
        initComponents();
        oldColor = myPanel.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        chkRed = new javax.swing.JCheckBox();
        chkGreen = new javax.swing.JCheckBox();
        chkBlue = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel.setBackground(new java.awt.Color(51, 51, 51));

        chkRed.setBackground(new java.awt.Color(51, 51, 51));
        chkRed.setForeground(new java.awt.Color(255, 255, 255));
        chkRed.setText("Red");
        chkRed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkRedItemStateChanged(evt);
            }
        });

        chkGreen.setBackground(new java.awt.Color(51, 51, 51));
        chkGreen.setForeground(new java.awt.Color(255, 255, 255));
        chkGreen.setText("Green");
        chkGreen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkGreenItemStateChanged(evt);
            }
        });

        chkBlue.setBackground(new java.awt.Color(51, 51, 51));
        chkBlue.setForeground(new java.awt.Color(255, 255, 255));
        chkBlue.setText("Blue");
        chkBlue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBlueItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(chkRed, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(chkBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chkRed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGreen)
                    .addComponent(chkBlue))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        myPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chkBlue, chkGreen, chkRed});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkRedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkRedItemStateChanged
        selectColor();
    }//GEN-LAST:event_chkRedItemStateChanged

    private void chkGreenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkGreenItemStateChanged
        selectColor();
    }//GEN-LAST:event_chkGreenItemStateChanged

    private void chkBlueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBlueItemStateChanged
        selectColor();
    }//GEN-LAST:event_chkBlueItemStateChanged

    private void selectColor(){
        if(chkRed.isSelected())
            myPanel.setBackground(Color.RED);
        else if(chkGreen.isSelected())
            myPanel.setBackground(Color.GREEN);
        else if(chkBlue.isSelected())
            myPanel.setBackground(Color.BLUE);
        else if(chkRed.isSelected() && chkGreen.isSelected())
            myPanel.setBackground(Color.YELLOW);
        else if(chkRed.isSelected() && chkBlue.isSelected())
            myPanel.setBackground(new Color(255,0,255));
        else if(chkGreen.isSelected() && chkBlue.isSelected())
            myPanel.setBackground(new Color(0,255,255));
        else if(chkRed.isSelected() && chkGreen.isSelected() && chkBlue.isSelected())
            myPanel.setBackground(Color.WHITE);
        else
            myPanel.setBackground(oldColor);
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_ColorChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_ColorChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_ColorChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_ColorChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_ColorChanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBlue;
    private javax.swing.JCheckBox chkGreen;
    private javax.swing.JCheckBox chkRed;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables
}
