/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Bhuwan.gui.SwingDemo;

import java.awt.event.KeyEvent;

/**
 *
 * @author Bhuwan Pandey
 */
public class KmToM_Conveter extends javax.swing.JFrame {

    double convert;
    double getKM;
    public KmToM_Conveter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblKiloMeter = new javax.swing.JLabel();
        lblMeter = new javax.swing.JLabel();
        txtKiloMeter = new javax.swing.JTextField();
        txtMeter = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblErr = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KmToM Calculator");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Curlz MT", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblKiloMeter.setBackground(new java.awt.Color(51, 51, 51));
        lblKiloMeter.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblKiloMeter.setForeground(new java.awt.Color(255, 255, 255));
        lblKiloMeter.setText("Enter KM");
        lblKiloMeter.setToolTipText("Enter Length in Kilometer");

        lblMeter.setBackground(new java.awt.Color(51, 51, 51));
        lblMeter.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMeter.setForeground(new java.awt.Color(255, 255, 255));
        lblMeter.setText("In Meter");
        lblMeter.setToolTipText("Length In Meter");

        txtKiloMeter.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        txtKiloMeter.setToolTipText("Enter Length in Kilometer");
        txtKiloMeter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKiloMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKiloMeterKeyPressed(evt);
            }
        });

        txtMeter.setEditable(false);
        txtMeter.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        txtMeter.setToolTipText("Length In Meter");
        txtMeter.setBorder(null);

        btnConvert.setBackground(new java.awt.Color(153, 153, 255));
        btnConvert.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        btnConvert.setText("Convert");
        btnConvert.setToolTipText("Convert");
        btnConvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        btnConvert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConvertEnter(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 51, 51));
        btnClear.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setToolTipText("Clear All Text");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(153, 0, 0));
        btnQuit.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("Quit");
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblErr.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        lblErr.setForeground(new java.awt.Color(255, 51, 51));
        lblErr.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKiloMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMeter)
                                    .addComponent(txtKiloMeter)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClear, btnConvert, btnQuit});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKiloMeter)
                    .addComponent(lblKiloMeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMeter))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnConvert, btnQuit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFunction();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
       convertFunction();
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnConvertEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvertEnter
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
           convertFunction();
    }//GEN-LAST:event_btnConvertEnter

    private void txtKiloMeterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKiloMeterKeyPressed
        btnConvertEnter(evt);
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            clearFunction();
        //keyboard ShortCut for Clear Function
        /*
         * @shortcut key 
         * for Clear : press CTRL + C
        */
        if((evt.getKeyCode() == KeyEvent.CTRL_DOWN_MASK) && (evt.getKeyCode() == KeyEvent.VK_C))
            clearFunction();
        
    }//GEN-LAST:event_txtKiloMeterKeyPressed

    private void clearFunction(){
        txtKiloMeter.setText("");
        txtMeter.setText("");
        txtKiloMeter.requestFocus();
    }
    private void convertFunction(){
         try{
            getKM = Double.parseDouble(txtKiloMeter.getText());
        }catch(NumberFormatException nfe){
            lblErr.setText("Please Enter Numerical Value Only");
        }
        convert = getKM * 1000;
        txtMeter.setText(String.valueOf(convert));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KmToM_Conveter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KmToM_Conveter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KmToM_Conveter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KmToM_Conveter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KmToM_Conveter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnQuit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErr;
    private javax.swing.JLabel lblKiloMeter;
    private javax.swing.JLabel lblMeter;
    private javax.swing.JTextField txtKiloMeter;
    private javax.swing.JTextField txtMeter;
    // End of variables declaration//GEN-END:variables
}
