/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BMS.GUI;

import BMS.DAO.BusDAO;
import BMS.DAO.RouteDAO;
import BMS.POJO.BusPojo;
import BMS.POJO.RoutePojo;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;

/**
 *
 * @author Bhuwan Pandey
 */
public class ManageRouteFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageRouteFrame
     */
    DefaultTableModel tb;
    public ManageRouteFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        String userDir = System.getProperty("user.dir");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = tk.getImage(userDir + "\\icon\\route.png");
        super.setIconImage(img);
        loadRouteId();
        loadRoutes();
        loadBusNo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSource = new app.bolivia.swing.JCTextField();
        txtCost = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDelete = new rojerusan.RSMaterialButtonCircle();
        btnAdd = new rojerusan.RSMaterialButtonCircle();
        btnUpdate = new rojerusan.RSMaterialButtonCircle();
        jcBusNo = new javax.swing.JComboBox<>();
        jcDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTime = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDestination = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoute = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Routes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(218, 62, 82));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_back_to_32px.png"))); // NOI18N
        lblBack.setText("Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel3.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_badge_50px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 50));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROUTE ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        txtId.setBackground(new java.awt.Color(102, 102, 255));
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtId.setPhColor(new java.awt.Color(204, 204, 204));
        txtId.setPlaceholder("Enter Route ID");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_user_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 50));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Source");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        txtSource.setBackground(new java.awt.Color(102, 102, 255));
        txtSource.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtSource.setForeground(new java.awt.Color(255, 255, 255));
        txtSource.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtSource.setPhColor(new java.awt.Color(204, 204, 204));
        txtSource.setPlaceholder("Enter City Name ");
        jPanel1.add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 50));

        txtCost.setBackground(new java.awt.Color(102, 102, 255));
        txtCost.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtCost.setForeground(new java.awt.Color(255, 255, 255));
        txtCost.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtCost.setPhColor(new java.awt.Color(204, 204, 204));
        txtCost.setPlaceholder("Enter Cost per Seat");
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        jPanel1.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 280, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_aircraft_seat_window_50px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 50));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Departure Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_Double_Decker_Bus_50px_5.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 50, 50));

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bus Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 130, 30));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 150, 50));

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 150, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 150, 50));

        jcBusNo.setBackground(new java.awt.Color(102, 102, 255));
        jcBusNo.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.add(jcBusNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 270, 40));
        jPanel1.add(jcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 150, 40));

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cost");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, 20));

        jLabel13.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Departure Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, 20));

        txtTime.setBackground(new java.awt.Color(102, 102, 255));
        txtTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtTime.setPhColor(new java.awt.Color(204, 204, 204));
        txtTime.setPlaceholder("Enter Departure Time");
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 280, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_aircraft_seat_window_50px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_aircraft_seat_window_50px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 50));

        txtDestination.setBackground(new java.awt.Color(102, 102, 255));
        txtDestination.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtDestination.setForeground(new java.awt.Color(255, 255, 255));
        txtDestination.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtDestination.setPhColor(new java.awt.Color(204, 204, 204));
        txtDestination.setPlaceholder("Enter City Name ");
        jPanel1.add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 280, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_user_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 50));

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Destination");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 760));

        jPanel2.setBackground(new java.awt.Color(255, 252, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbRoute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route ID", "Source", "Destination", "Bus Number", "Date", "Time", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoute.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbRoute.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbRoute.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbRoute.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        tbRoute.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        tbRoute.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbRoute.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbRoute.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbRoute.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbRoute.setRowHeight(40);
        tbRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRouteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRoute);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 1040, 610));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_management_30px_3.png"))); // NOI18N
        jLabel1.setText("  Manage Routes");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 303, 44));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(329, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 5));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 1080, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            RoutePojo route = new RoutePojo();
            route.setRid(txtId.getText());
            route.setSource(txtSource.getText().trim());
            route.setDestination(txtDestination.getText().trim());
            route.setBusno(jcBusNo.getSelectedItem().toString());
            long date = jcDate.getDate().getTime();
            route.setDepartureDate(new java.sql.Date(date));
            route.setDepartureTime(txtTime.getText().trim());
            int cost = Integer.parseInt(txtCost.getText().trim());
            route.setCost(cost);
            boolean result = RouteDAO.updateRoute(route);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadRouteId();
                tb.setRowCount(0);
                loadRoutes();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not updated","Incomplete",JOptionPane.ERROR_MESSAGE);

        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in salary","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            RoutePojo route = new RoutePojo();
            route.setRid(txtId.getText());
            route.setSource(txtSource.getText().trim());
            route.setDestination(txtDestination.getText().trim());
            route.setBusno(jcBusNo.getSelectedItem().toString());
            route.setDepartureDate(new java.sql.Date(jcDate.getDate().getTime()));
            route.setDepartureTime(txtTime.getText().toString());
            int cost = Integer.parseInt(txtCost.getText().trim());
            route.setCost(cost);
            boolean result = RouteDAO.addRoute(route);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Added Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadRouteId();
                tb.setRowCount(0);
                loadRoutes();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Record not Added Sucessfully","UnSucess",JOptionPane.ERROR_MESSAGE);

        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in salary","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = txtId.getText().trim();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Select Route First", "Incomplete", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            boolean result = RouteDAO.deleteRoute(id);
            if(result){
                JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadRouteId();
                tb.setRowCount(0);
                loadRoutes();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not deleted","Incomplete",JOptionPane.ERROR_MESSAGE);

        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        ManagerFrame mf = new ManagerFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void tbRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRouteMouseClicked
        try{
            int row = tbRoute.getSelectedRow();
            txtId.setText(tb.getValueAt(row, 0).toString());
            txtSource.setText(tb.getValueAt(row, 1).toString());
            txtDestination.setText(tb.getValueAt(row, 2).toString());
            jcBusNo.setSelectedItem(tb.getValueAt(row, 3).toString());
            jcDate.setDate((java.sql.Date)tb.getValueAt(row, 4));
            txtTime.setText(tb.getValueAt(row, 5).toString());
            txtCost.setText(tb.getValueAt(row, 6).toString());
        }catch(NullPointerException npe){
            System.out.println("Sorry");
            npe.printStackTrace();
        }
    }//GEN-LAST:event_tbRouteMouseClicked

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRouteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRouteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRouteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRouteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRouteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btnAdd;
    private rojerusan.RSMaterialButtonCircle btnDelete;
    private rojerusan.RSMaterialButtonCircle btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcBusNo;
    private com.toedter.calendar.JDateChooser jcDate;
    private javax.swing.JLabel lblBack;
    private rojerusan.RSTableMetro tbRoute;
    private app.bolivia.swing.JCTextField txtCost;
    private app.bolivia.swing.JCTextField txtDestination;
    private app.bolivia.swing.JCTextField txtId;
    private app.bolivia.swing.JCTextField txtSource;
    private app.bolivia.swing.JCTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private boolean isEmpty() {
        String source = txtSource.getText().trim();
        String cost = txtCost.getText().trim();
        String time = txtTime.getText().trim();
        String destination = txtDestination.getText().trim();
        return !(source.isEmpty() || cost.isEmpty() || time.isEmpty() || destination.isEmpty());
    }

    private void clearText() {
        txtId.setText("");
        txtSource.setText("");
        jcBusNo.setSelectedIndex(0);
        jcDate.cleanup();
        txtTime.setText("");
        txtCost.setText("");
        txtDestination.setText("");
    }

    
    private void loadRoutes() {
        try{
            List<RoutePojo> routeLists = RouteDAO.getAllRoutes();
            tb = (DefaultTableModel)tbRoute.getModel();
            Object []route = new Object[7];
            for(RoutePojo routeList: routeLists){
                route[0] = routeList.getRid();
                route[1] = routeList.getSource();
                route[2] = routeList.getDestination();
                route[3] = routeList.getBusno();
                route[4] = routeList.getDepartureDate();
                route[5] = routeList.getDepartureTime();
                route[6] = routeList.getCost();
                tb.addRow(route);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to connect with database", "Error", JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
        }    
    }

    private void loadRouteId() {
        try{
            String routeId = RouteDAO.getRouteId();
            txtId.setText(routeId);
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get route id.","Error",JOptionPane.ERROR);
            se.printStackTrace();
            return;
        }
    }

    private void loadBusNo() {
        try{
            List<BusPojo> allBusDetails = BusDAO.getBusDetails();
                      
            for(BusPojo allBus : allBusDetails){
                String id = allBus.getBusNo();
                jcBusNo.addItem(id);
            }
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get bus id.","Error",JOptionPane.ERROR);
            se.printStackTrace();
            return;
        }
    }
}
