/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BMS.GUI;

import BMS.DAO.BusDAO;
import BMS.POJO.BusPojo;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhuwan Pandey
 */
public class ManageBusFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageBusFrame
     */
    DefaultTableModel tb;
    public ManageBusFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        String userDir = System.getProperty("user.dir");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = tk.getImage(userDir + "\\icon\\bus.png");
        super.setIconImage(img);
        loadBuses();
        loadBusId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new app.bolivia.swing.JCTextField();
        txtNoOfSeat = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDelete = new rojerusan.RSMaterialButtonCircle();
        btnAdd = new rojerusan.RSMaterialButtonCircle();
        btnUpdate = new rojerusan.RSMaterialButtonCircle();
        jcType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBus = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busses");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(218, 62, 82));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_back_to_32px.png"))); // NOI18N
        lblBack.setText("Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel3.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_badge_50px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 50));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bus Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 20));

        txtId.setBackground(new java.awt.Color(102, 102, 255));
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtId.setPhColor(new java.awt.Color(204, 204, 204));
        txtId.setPlaceholder("Enter Bus Number");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_user_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 50));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        txtName.setBackground(new java.awt.Color(102, 102, 255));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtName.setPhColor(new java.awt.Color(204, 204, 204));
        txtName.setPlaceholder("Enter Bus Company Name");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 50));

        txtNoOfSeat.setBackground(new java.awt.Color(102, 102, 255));
        txtNoOfSeat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNoOfSeat.setForeground(new java.awt.Color(255, 255, 255));
        txtNoOfSeat.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtNoOfSeat.setPhColor(new java.awt.Color(204, 204, 204));
        txtNoOfSeat.setPlaceholder("Enter Total Number of Seats");
        jPanel1.add(txtNoOfSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 280, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_aircraft_seat_window_50px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 50));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Number of Seats");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_Double_Decker_Bus_50px_5.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 50, 50));

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 90, 30));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 150, 50));

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 150, 50));

        jcType.setBackground(new java.awt.Color(102, 102, 255));
        jcType.setForeground(new java.awt.Color(102, 102, 255));
        jcType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "AC" }));
        jPanel1.add(jcType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 630));

        jPanel2.setBackground(new java.awt.Color(255, 252, 249));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Number", "Company Name", "Total Seats", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBus.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbBus.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbBus.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbBus.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        tbBus.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        tbBus.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbBus.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbBus.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbBus.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbBus.setRowHeight(40);
        tbBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBus);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 760, 460));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_management_30px_3.png"))); // NOI18N
        jLabel1.setText("  Manage Buses");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 303, 44));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(329, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 5));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 820, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        ManagerFrame mf = new ManagerFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = txtId.getText().trim();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Select Bus First", "Incomplete", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            boolean result = BusDAO.deleteBus(id);
            if(result){
                JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadBusId();
                tb.setRowCount(0);
                loadBuses();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not deleted","Incomplete",JOptionPane.ERROR_MESSAGE);

        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            BusPojo bus = new BusPojo();
            bus.setBusNo(txtId.getText());
            bus.setBusCompany(txtName.getText().trim());
            int seats = Integer.parseInt(txtNoOfSeat.getText().trim());
            bus.setSeat(seats);
            bus.setType(jcType.getSelectedItem().toString());
            boolean result = BusDAO.addBus(bus);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Added Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadBusId();
                tb.setRowCount(0);
                loadBuses();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Record not Added Sucessfully","UnSucess",JOptionPane.ERROR_MESSAGE);

        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in salary","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            BusPojo bus = new BusPojo();
            bus.setBusNo(txtId.getText().trim());
            bus.setBusCompany(txtName.getText());
            int seats = Integer.parseInt(txtNoOfSeat.getText());
            bus.setSeat(seats);
            bus.setType(jcType.getSelectedItem().toString());
            
            boolean result = BusDAO.updateBus(bus);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadBusId();
                tb.setRowCount(0);
                loadBuses();
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not updated","Incomplete",JOptionPane.ERROR_MESSAGE);

        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in salary","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBusMouseClicked
        try{
            int row = tbBus.getSelectedRow();
            txtId.setText(tb.getValueAt(row, 0).toString());
            txtName.setText(tb.getValueAt(row, 1).toString());
            txtNoOfSeat.setText(tb.getValueAt(row, 2).toString());
            jcType.setSelectedItem(tb.getValueAt(row, 3).toString()); 
        }catch(NullPointerException npe){
            System.out.println("Sorry");
            npe.printStackTrace();
        }

    }//GEN-LAST:event_tbBusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBusFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btnAdd;
    private rojerusan.RSMaterialButtonCircle btnDelete;
    private rojerusan.RSMaterialButtonCircle btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcType;
    private javax.swing.JLabel lblBack;
    private rojerusan.RSTableMetro tbBus;
    private app.bolivia.swing.JCTextField txtId;
    private app.bolivia.swing.JCTextField txtName;
    private app.bolivia.swing.JCTextField txtNoOfSeat;
    // End of variables declaration//GEN-END:variables

    private boolean isEmpty() {
        String name = txtName.getText().trim();
        String seats = txtNoOfSeat.getText().trim();
        return !(name.isEmpty() || seats.isEmpty());
    }

    private void clearText() {
        txtName.setText("");
        txtNoOfSeat.setText("");
        jcType.setSelectedIndex(0);
    }

    private void loadBusId() {
        try{
            String busId = BusDAO.getBusId();
            txtId.setText(busId);
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get bus id.","Error",JOptionPane.ERROR);
            se.printStackTrace();
            return;
        }
    }
    
    private void loadBuses() {
         try{
            List<BusPojo> busLists = BusDAO.getBusDetails();
            tb = (DefaultTableModel)tbBus.getModel();
            Object []bus = new Object[4];
            for(BusPojo busList: busLists){
                bus[0] = busList.getBusNo();
                bus[1] = busList.getBusCompany();
                bus[2] = busList.getSeat();
                bus[3] = busList.getType();
                tb.addRow(bus);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to connect with database", "Error", JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
        }
    }
}
