/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BMS.GUI;

import BMS.DAO.BusDAO;
import BMS.DAO.PassengerDAO;
import BMS.DAO.RouteDAO;
import BMS.DAO.TicketDAO;
import BMS.POJO.BusPojo;
import BMS.POJO.PassengerPojo;
import BMS.POJO.RoutePojo;
import BMS.POJO.TicketPojo;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Bhuwan Pandey
 */
public class TicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form TicketFrame
     */
    DefaultTableModel tb;
    public TicketFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        String userDir = System.getProperty("user.dir");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = tk.getImage(userDir + "\\icon\\ticket.png");
        super.setIconImage(img);
        loadTickets();
        loadTicketNo();
        loadOtherDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTickets = new rojerusan.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblBack1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnDelete = new rojerusan.RSMaterialButtonCircle();
        btnAdd = new rojerusan.RSMaterialButtonCircle();
        btnUpdate = new rojerusan.RSMaterialButtonCircle();
        jcName = new javax.swing.JComboBox<>();
        jcDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcSource = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcDestination = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtPrice = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcBusNo = new javax.swing.JComboBox<>();
        jcTime = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Tickets");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 252, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(218, 62, 82));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_back_to_32px.png"))); // NOI18N
        lblBack.setText("Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel3.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_two_tickets_30px_1.png"))); // NOI18N
        jLabel1.setText("  Book Tickets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 303, 44));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(329, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 5));

        tbTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket", "PID", "Name", "Day", "Time", "Bus No", "Source", "Destination", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTickets.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbTickets.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbTickets.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbTickets.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        tbTickets.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        tbTickets.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbTickets.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbTickets.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbTickets.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbTickets.setRowHeight(40);
        tbTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTicketsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTickets);
        if (tbTickets.getColumnModel().getColumnCount() > 0) {
            tbTickets.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbTickets.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbTickets.getColumnModel().getColumn(2).setPreferredWidth(400);
            tbTickets.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbTickets.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbTickets.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbTickets.getColumnModel().getColumn(6).setPreferredWidth(180);
            tbTickets.getColumnModel().getColumn(7).setPreferredWidth(180);
            tbTickets.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1150, 260));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(218, 62, 82));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblBack1.setForeground(new java.awt.Color(255, 255, 255));
        lblBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_back_to_32px.png"))); // NOI18N
        lblBack1.setText("Back");
        lblBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack1MouseClicked(evt);
            }
        });
        jPanel5.add(lblBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_badge_50px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 50));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ticket Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        txtId.setBackground(new java.awt.Color(102, 102, 255));
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtId.setPhColor(new java.awt.Color(204, 204, 204));
        txtId.setPlaceholder("Enter Passenger ID");
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_user_50px_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 50));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 20));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Day");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_bus_50px_4.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, 50));

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bus No");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 90, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_sunday_50px.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 50));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("CANCEL TICKET");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 190, 50));

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setText("Book Ticket");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 190, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setText("UPDATE TICKET");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 190, 50));

        jcName.setBackground(new java.awt.Color(102, 102, 255));
        jcName.setForeground(new java.awt.Color(102, 102, 255));
        jcName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNameActionPerformed(evt);
            }
        });
        jPanel2.add(jcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 270, 40));
        jPanel2.add(jcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 210, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_time_50px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, 50));

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Time");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_back_to_32px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, 50));

        jcSource.setBackground(new java.awt.Color(102, 102, 255));
        jcSource.setForeground(new java.awt.Color(102, 102, 255));
        jPanel2.add(jcSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 270, 40));

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Source");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 90, 30));

        jLabel15.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Destination");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 160, 30));

        jcDestination.setBackground(new java.awt.Color(102, 102, 255));
        jcDestination.setForeground(new java.awt.Color(102, 102, 255));
        jPanel2.add(jcDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 270, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_destination_50px.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 50));

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(102, 102, 255));
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txtPrice.setPhColor(new java.awt.Color(204, 204, 204));
        txtPrice.setPlaceholder("Enter Passenger Name");
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 280, 40));

        jLabel17.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Price");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BMS/Images/icons8_cost_50px.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, 50));

        jcBusNo.setBackground(new java.awt.Color(102, 102, 255));
        jcBusNo.setForeground(new java.awt.Color(102, 102, 255));
        jcBusNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBusNoActionPerformed(evt);
            }
        });
        jPanel2.add(jcBusNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 270, 40));

        jcTime.setBackground(new java.awt.Color(102, 102, 255));
        jcTime.setForeground(new java.awt.Color(102, 102, 255));
        jcTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTimeActionPerformed(evt);
            }
        });
        jPanel2.add(jcTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 270, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        EmployeeFrame ef = new EmployeeFrame();
        ef.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBackMouseClicked

    private void tbTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTicketsMouseClicked
        try{
            int row = tbTickets.getSelectedRow();
            txtId.setText(tb.getValueAt(row, 0).toString());
            jcName.setSelectedItem(tb.getValueAt(row, 1).toString());
            jcDate.setDate((java.sql.Date)tb.getValueAt(row, 3));
            jcTime.setSelectedItem(tb.getValueAt(row, 4));
            jcBusNo.setSelectedItem(tb.getValueAt(row, 5));
            jcSource.setSelectedItem(tb.getValueAt(row, 6));
            jcDestination.setSelectedItem(tb.getValueAt(row, 7));
            txtPrice.setText(tb.getValueAt(row, 8).toString());
        }catch(NullPointerException npe){
            System.out.println("Sorry");
            npe.printStackTrace();
        }
    }//GEN-LAST:event_tbTicketsMouseClicked

    private void lblBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseClicked
        EmployeeFrame ef = new EmployeeFrame();
        ef.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblBack1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = txtId.getText().trim();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Select Ticket Number First", "Incomplete", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try{
            boolean result = TicketDAO.calcelTicket(id);
            if(result){
                JOptionPane.showMessageDialog(null, "Record Deleted Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadTicketNo();
                tb.setRowCount(0);
                loadTickets();
                
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not deleted","Incomplete",JOptionPane.ERROR_MESSAGE);

        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in Database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            TicketPojo ticket = new TicketPojo(); 
            ticket.setTicket_no(txtId.getText());
            ticket.setPid(jcName.getSelectedItem().toString());
            ticket.setDay(new java.sql.Date(jcDate.getDate().getTime()));
            ticket.setTime(jcTime.getSelectedItem().toString());
            ticket.setBusno(jcBusNo.getSelectedItem().toString());
            ticket.setSource(jcSource.getSelectedItem().toString());
            ticket.setDestination(jcDestination.getSelectedItem().toString());
            int price = Integer.parseInt(txtPrice.getText());
            ticket.setPrice(price);
            boolean result = TicketDAO.bookTicket(ticket);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Added Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadTicketNo();
                tb.setRowCount(0);
                loadTickets();
                
                return;
            }else
            JOptionPane.showMessageDialog(null, "Sorry Record is not Added","Incomplete",JOptionPane.ERROR_MESSAGE);

        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in Database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in price","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill all the value properly","Incomplete",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            TicketPojo ticket = new TicketPojo();
            ticket.setTicket_no(txtId.getText());
            ticket.setPid(jcName.getSelectedItem().toString());
            long date = jcDate.getDate().getTime();
            ticket.setDay(new java.sql.Date(date));
            ticket.setTime(jcTime.getSelectedItem().toString());
            ticket.setSource(jcSource.getSelectedItem().toString());
            ticket.setDestination(jcDestination.getSelectedItem().toString());
            int price = Integer.parseInt(txtPrice.getText());
            ticket.setPrice(price);
            boolean result = TicketDAO.updateTicket(ticket);
            if(result == true){
                JOptionPane.showMessageDialog(null, "Record Updated Sucessfully","Sucess",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                loadTicketNo();
                tb.setRowCount(0);
                
                loadTickets();
                
                return;
            }else
                JOptionPane.showMessageDialog(null, "Sorry Record is not updated","Incomplete",JOptionPane.ERROR_MESSAGE);

        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Error in Database","Incomplete",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please Enter numeric value in salary","Incomplete",JOptionPane.ERROR_MESSAGE);
            nfe.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jcNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcNameActionPerformed

    private void jcBusNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBusNoActionPerformed
        try{
            List<RoutePojo> allRouteDetails = RouteDAO.getAllRoutes();
                      
            clearField();
            allRouteDetails.forEach((allDetails) -> {
                if(jcBusNo.getSelectedItem().equals(allDetails.getBusno())){
                    
                    Date date = allDetails.getDepartureDate();
                    String time = allDetails.getDepartureTime();
                    String source = allDetails.getSource();
                    String destination = allDetails.getDestination();
                    int price = allDetails.getCost();
                    jcDate.setDate(date);
                    jcTime.addItem(time);
                    jcSource.addItem(source);
                    jcDestination.addItem(destination);
                    txtPrice.setText(String.valueOf(price));
                }
            });
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get bus id.","Error",JOptionPane.ERROR);
            se.printStackTrace();
            return;
        }
    }//GEN-LAST:event_jcBusNoActionPerformed

    private void jcTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btnAdd;
    private rojerusan.RSMaterialButtonCircle btnDelete;
    private rojerusan.RSMaterialButtonCircle btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcBusNo;
    private com.toedter.calendar.JDateChooser jcDate;
    private javax.swing.JComboBox<String> jcDestination;
    private javax.swing.JComboBox<String> jcName;
    private javax.swing.JComboBox<String> jcSource;
    private javax.swing.JComboBox<String> jcTime;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBack1;
    private rojerusan.RSTableMetro tbTickets;
    private app.bolivia.swing.JCTextField txtId;
    private app.bolivia.swing.JCTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private boolean isEmpty() {
        String price = txtPrice.getText().trim();
        return !( price.isEmpty());
    }

    private void clearText() {
        try{
        jcName.setSelectedIndex(0);
        jcTime.setSelectedIndex(0);
        jcBusNo.setSelectedIndex(0);
        jcSource.setSelectedIndex(0);
        jcDestination.setSelectedIndex(0);
        txtPrice.setText("");
        }catch (IllegalArgumentException iae){
            return;
        }
    }

    private void loadTicketNo() {
        try{
            String ticketId = TicketDAO.getTicketId();
            txtId.setText(ticketId);
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get Ticket Number.","Error",JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
            return;
        }
    }

    private void loadTickets() {
        try{
            List<TicketPojo> ticketLists = TicketDAO.getAllTickets();
            Map<String,String> passengerLists = PassengerDAO.getPassengerName();
            tb = (DefaultTableModel)tbTickets.getModel();
            Object []ticket = new Object[9];
            for(TicketPojo ticketList: ticketLists){
                ticket[0] = ticketList.getTicket_no();
                ticket[1] = ticketList.getPid();
                if(passengerLists.containsKey(ticketList.getPid())){
                    ticket[2] = passengerLists.get(ticketList.getPid());
                }
                ticket[3] = ticketList.getDay();
                ticket[4] = ticketList.getTime();
                ticket[5] = ticketList.getBusno();
                ticket[6] = ticketList.getSource();
                ticket[7] = ticketList.getDestination();
                ticket[8] = ticketList.getPrice();
                tb.addRow(ticket);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to connect with database", "Error", JOptionPane.ERROR_MESSAGE);
            se.printStackTrace();
        }  
    }

    private void loadOtherDetails() {
        try{
            List<BusPojo> allBusDetails = BusDAO.getBusDetails();
            List<PassengerPojo> allPassengers = PassengerDAO.getAllPassenger();
            for(BusPojo allBus : allBusDetails){
                String id = allBus.getBusNo();
                jcBusNo.addItem(id);
            }
            for(PassengerPojo allPassenger : allPassengers){
                String pid = allPassenger.getPid();
                jcName.addItem(pid);
            }
        }
        catch(SQLException se){
            JOptionPane.showMessageDialog(null, "Unable to get bus id.","Error",JOptionPane.ERROR);
            se.printStackTrace();
            return;
        }
    
    }

    private void clearField() {
        jcTime.removeAllItems();
        jcSource.removeAllItems();
        jcDestination.removeAllItems();
    }
}
